// <auto-generated />
using System;
using FirstApi.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FirstApi.Migrations
{
    [DbContext(typeof(SystemDbContext))]
    [Migration("20240716063410_InitialDB")]
    partial class InitialDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FirstApi.Domain.Entities.Employer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("cargo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<double?>("paymentTotal")
                        .IsRequired()
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Employers", (string)null);
                });

            modelBuilder.Entity("FirstApi.Domain.Entities.Employer", b =>
                {
                    b.OwnsOne("FirstApi.Domain.ValueObjects.Payment", "payment", b1 =>
                        {
                            b1.Property<int>("EmployerId")
                                .HasColumnType("integer");

                            b1.Property<double>("benefits")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("double precision")
                                .HasDefaultValue(0.0)
                                .HasColumnName("benefits");

                            b1.Property<double>("salary")
                                .HasColumnType("double precision")
                                .HasColumnName("salary");

                            b1.HasKey("EmployerId");

                            b1.ToTable("Employers");

                            b1.WithOwner()
                                .HasForeignKey("EmployerId");
                        });

                    b.Navigation("payment");
                });
#pragma warning restore 612, 618
        }
    }
}
